# -*- coding: utf-8 -*-
"""Varsayılan içerik sayfaları (Hakkımızda, KVKK, İletişim, SSS, İade, Gizlilik, Mesafeli Satış,
Ön Bilgilendirme) — BEYAZ ETİKET şablonları. Firma-özel hiçbir değer içermez; {{store_name}},
{{company_name}}, {{address}}, {{phone}}, {{email}}, {{iban}}, {{tax_office}}, {{tax_number}},
{{mersis_number}}, {{site}} yer tutucuları seed anında (routes/pages.py) Firma Bilgileri'nden
doldurulur. Hukuki metinler taslaktır; yayına almadan önce işletmenin hukuk danışmanınca
gözden geçirilmelidir. Admin > Sayfalar bölümünden düzenlenebilir."""

DEFAULT_PAGES = [{'slug': 'hakkimizda',
  'title': 'Hakkımızda',
  'meta_title': 'Hakkımızda | {{store_name}}',
  'meta_description': '{{store_name}} hakkında: markamız, değerlerimiz ve hikâyemiz.',
  'content': '<p style="margin-top:20px; text-align:center;"><span style="font-size:20px;">HAKKIMIZDA</span></p>\n'
             '\n'
             '<p style="font-size:18px; line-height:1.8; color:#111; margin-top:20px; '
             'text-align:center;">{{store_name}}, müşterilerine kaliteli ürünleri güvenli ve keyifli bir alışveriş '
             'deneyimiyle sunmak için kuruldu.</p>\n'
             '\n'
             '<p style="font-size:18px; line-height:1.8; color:#111; text-align:center;">Bu sayfanın içeriğini Admin '
             '&gt; Sayfalar bölümünden markanızın hikâyesiyle güncelleyebilirsiniz.</p>'},
 {'slug': 'kvkk',
  'title': 'KVKK Aydınlatma Metni',
  'meta_title': 'KVKK Aydınlatma Metni | {{store_name}}',
  'meta_description': '{{company_name}} kişisel verilerin korunması (KVKK) aydınlatma metni.',
  'content': '<p>Kişisel Verilerin Korunmasına İlişkin Bilgilendirme;</p>\n'
             '\n'
             "<p>{{company_name}} olarak kişisel verilerinizin 6698 sayılı Kişisel Verilerin Korunması Kanunu'na "
             '(“Kanun”) uygun olarak işlenerek, muhafaza edilmesine büyük önem veriyoruz. Müşterilerimizi kişisel '
             "verileri toplama, işleme, aktarma amacımız ve yöntemlerimiz ve buna bağlı olarak sizlerin Kanun'dan "
             'kaynaklanan haklarınızla ilgili bilgilendirmek isteriz.</p>\n'
             '\n'
             '<p>&nbsp;</p>\n'
             '\n'
             '<p>1. Kişisel verilerin toplanmasına ilişkin yöntemler</p>\n'
             '\n'
             '<p>{{company_name}} olarak, veri sorumlusu sıfatıyla, mevzuattan kaynaklanan yasal yükümlülüklerimiz '
             'çerçevesinde; markalarımızın hizmetlerinden faydalanabilmeniz, onayınız halinde kampanyalarımız hakkında '
             'sizleri bilgilendirmek, öneri ve şikayetlerinizi kayıt altına alabilmek, sizlere daha iyi hizmet '
             'standartları oluşturabilmek, {{company_name}} ticari ve iş stratejilerinin belirlenmesi ve uygulanması '
             'gibi amaçlarla kişisel verilerinizi sözlü, internet sitesi, sosyal medya mecraları, mobil uygulamalar '
             've benzeri vasıtalarla sözlü, yazılı ya da elektronik yöntemlerle toplamaktayız.</p>\n'
             '\n'
             '<p>&nbsp;</p>\n'
             '\n'
             '<p>2. Kişisel verilerin işlenmesi ve işleme amaçları</p>\n'
             '\n'
             '<p>{{company_name}} olarak, veri sorumlusu sıfatı ile çağrı merkezlerimiz, yazılı iletişim kanallarımız, '
             'sosyal medya sayfalarımız, mobil iletişim kanalları, mağaza içi iletişim kanalları ve/veya bunlarla '
             'sınırlı olmamak üzere her türlü kanallar aracılığı ile; onayınız dahilinde elde ettiğimiz kişisel '
             've/veya özel nitelikli kişisel verileriniz tamamen veya kısmen elde edilebilir, kaydedilebilir, '
             'saklanabilir, depolanabilir, değiştirilebilir, güncellenebilir, periyodik olarak kontrol edilebilir, '
             'yeniden düzenlenebilir, sınıflandırılabilir, işlendikleri amaç için gerekli olan ya da ilgili kanunda '
             'öngörülen süre kadar muhafaza edilebilir, kanuni ya da hizmete bağlı fiili gereklilikler halinde '
             "{{company_name}}'nın birlikte çalıştığı özel-tüzel kişilerle ya da kanunen yükümlü olduğu kamu kurum "
             "ve kuruluşlarıyla ve/veya Türkiye'de veya yurt dışında mukim olan ilgili 3. kişi gerçek kişi/tüzel "
             'kişilerle paylaşılabilir/devredilebilir, kanuni ya da hizmete bağlı fiili gereklilikler halinde '
             'yurtdışına aktarılabilir.</p>\n'
             '\n'
             '<p>{{company_name}} müşterilerinin markalarımızın hizmetlerinden faydalanabilmesi, onayınız halinde '
             'kampanyalarımız hakkında sizleri bilgilendirmek, öneri ve şikayetlerinizi kayıt altına alabilmek, '
             'sizlere daha iyi hizmet standartları oluşturabilmek, {{company_name}} ticari ve iş stratejilerinin '
             'belirlenmesi ve uygulanması gibi amaçlarla ve her halükarda 6698 sayılı Kişisel Verilerin Korunması '
             'Kanunu ve ilgili mevzuata uygun olarak kişisel verilerinizi işleyebileceğimizi bilginize sunarız.</p>\n'
             '\n'
             '<p>&nbsp;</p>\n'
             '\n'
             '<p>3. Kişisel Verilerin Aktarılması</p>\n'
             '\n'
             "<p>{{company_name}}, söz konusu kişisel verilerinizi sadece; açık rızanıza istinaden veya Kanun'da "
             'belirtilen güvenlik ve gizlilik esasları çerçevesinde yeterli önlemler alınmak kaydıyla yurt içinde ve '
             'gerekli güvenlik önlemlerinin alınması kaydıyla yurt dışında, Şirket faaliyetlerinin yürütülmesi, '
             'veri sahipleri ile müşterilerimiz arasındaki iş ilişkisinin sağlanması ve/veya bu amaçla görüşmeler '
             'yapılması, hizmetler, fırsat ve olanaklar sunulması ve hizmet kalitesinin artırılması amacıyla; grup '
             'şirketlerimiz, iş ortaklarımız, faaliyetlerimizin gereği anlaşmalı olduğumuz ve hizmet sunduğumuz '
             'müşteriler, tedarikçiler, denetim şirketleri veya yasal bir zorunluluk gereği bu verileri talep etmeye '
             'yetkili olan kamu kurum veya kuruluşları, bunlarla sınırlı olmamak üzere ilgili diğer otoriteler ile '
             'paylaşabilecektir.</p>\n'
             '\n'
             '<p>&nbsp;</p>\n'
             '\n'
             "<p>4. Kişisel Veri Sahibinin KVK Kanunu'nun (“Kanun”) 11. maddesinde Sayılan Hakları</p>\n"
             '\n'
             '<p>{{company_name}} ilgili kişilerin aşağıdaki taleplerine karşılık verecektir:</p>\n'
             '\n'
             "<p>a) {{company_name}}'nın kendilerine ilişkin kişisel verileri işleyip işlemediğini ve hangi kişisel "
             'verileri işlediğini öğrenme,</p>\n'
             '\n'
             '<p>b) İşleme faaliyetinin amaçlarına ilişkin bilgi alma,</p>\n'
             '\n'
             "<p>c) {{company_name}}'nın yurt içinde veya yurt dışında kişisel verileri aktardığı üçüncü kişileri "
             'bilme,</p>\n'
             '\n'
             '<p>d) Kişisel verilerin eksik veya yanlış işlenmiş olması hâlinde bunların düzeltilmesini isteme,</p>\n'
             '\n'
             "<p>e) Kanun'a uygun olarak kişisel verilerin silinmesini veya yok edilmesini isteme,</p>\n"
             '\n'
             '<p>f) Kişisel verilerin düzeltilmesi, silinmesi ya da yok edilmesi talebi halinde; yapılan işlemlerin, '
             'kişisel verilerin aktarıldığı üçüncü kişilere bildirilmesini isteme,</p>\n'
             '\n'
             '<p>g) İşlenen verilerin münhasıran otomatik sistemler vasıtasıyla analiz edilmesi suretiyle kişinin '
             'kendisi aleyhine bir sonucun ortaya çıkmasına itiraz etme ve</p>\n'
             '\n'
             '<p>h) Kişisel verilerinin birer kopyasını alma.</p>\n'
             '\n'
             '<p>&nbsp;</p>\n'
             '\n'
             '<p>Görüş ve sorularınızla ilgili bizimle iletişime geçebilirsiniz.</p>\n'
             '\n'
             '<p>Ünvanı : {{company_name}}</p>\n'
             '\n'
             '<p>Telefonu: {{phone}}</p>\n'
             '\n'
             '<p>Mersis No: {{mersis_number}}</p>\n'
             '\n'
             '<p>Vergi Dairesi: {{tax_office}}</p>\n'
             '\n'
             '<p>Vergi Numarası: {{tax_number}}</p>\n'
             '\n'
             '<p>Adresi: -{{address}}</p>\n'
             '\n'
             '<p>Mail: <a href="mailto:{{email}}">{{email}}</a></p>\n'
             '\n'
             '<p>&nbsp;</p>\n'
             '\n'
             '<p>Gizlilik ve Güvenlik</p>\n'
             '\n'
             '<p>{{company_name}} Online Shop, müşterilerine daha iyi hizmet verebilmek amacıyla bazı kişisel '
             'bilgilerinizi (isim, yaş, ilgi alanlarınız, e-posta vb.) sizlerden talep etmektedir. {{company_name}} '
             'Online Shop sunucularında toplanan bu bilgiler, dönemsel kampanya çalışmaları, müşteri profillerine '
             'yönelik özel promosyon faaliyetlerinin kurgulanması ve istenmeyen e-postaların iletilmemesine yönelik '
             'müşteri "sınıflandırma" çalışmalarında sadece {{company_name}} Online Shop bünyesinde kullanılmaktadır. '
             '{{company_name}} Online Shop, üyelik formlarından topladığı bilgileri söz konusu üyenin haberi ya da '
             'aksi bir talimatı olmaksızın, üçüncü şahıslarla kesinlikle paylaşmamakta, faaliyet dışı hiçbir nedenle '
             'ticari amaçla kullanmamakta ve de satmamaktadır.</p>\n'
             '\n'
             '<p>&nbsp;</p>\n'
             '\n'
             '<p>Müşteri bilgileri, ancak resmi makamlarca bu bilgilerin talep edilmesi halinde ve yürürlükteki '
             'emredici mevzuat hükümleri gereğince resmi makamlara açıklama yapmak zorunda olduğu durumlarda resmi '
             'makamlara açıklanabilecektir.</p>\n'
             '\n'
             '<p>&nbsp;</p>\n'
             '\n'
             '<p>Müşterinin sisteme girdiği tüm bilgilere sadece müşteri ulaşabilmekte ve bu bilgileri sadece müşteri '
             'değiştirebilmektedir. Bir başkasının bu bilgilere ulaşması ve bunları değiştirmesi mümkün değildir. '
             'Ödeme sayfasında istenen kredi kartı bilgileriniz, siteden alışveriş yapan siz değerli müşterilerimizin '
             'güvenliğini en üst seviyede tutmak amacıyla hiçbir şekilde {{company_name}} Online Shop veya ona hizmet '
             'veren şirketlerin sunucularında tutulmamaktadır. Bu şekilde ödemeye yönelik tüm işlemlerin '
             '{{company_name}} Online Shop arayüzü üzerinden banka ve bilgisayarınız arasında gerçekleşmesi '
             'sağlanmaktadır.</p>\n'
             '\n'
             '<p>&nbsp;</p>\n'
             '\n'
             '<p>Çerez Kullanımı</p>\n'
             '\n'
             '<p>&nbsp;</p>\n'
             '\n'
             '<p>Çerezler, sitemizi ziyaret ettiğinizde bilgisayarınız ya da mobil cihazınıza (akıllı telefon veya '
             'tablet gibi) kaydedilen küçük metin dosyaları ya da bilgilerdir.</p>\n'
             '\n'
             '<p>&nbsp;</p>\n'
             '\n'
             '<p>Çerezleri, Sitelerimizin daha kolay kullanılması ve sizin ilgi ve ihtiyaçlarınıza göre ayarlanması '
             'için kullanıyoruz. İnternet siteleri bu çerez dosyaları okuyup yazabiliyorlar ve bu sayede tanınmanız ve '
             'size daha uygun bir internet sitesi sunulması amacıyla sizinle ilgili önemli bilgilerin hatırlanması '
             'sağlanıyor (tercih ayarlarınızın hatırlanması gibi).</p>\n'
             '\n'
             '<p>&nbsp;</p>\n'
             '\n'
             '<p>Çerezler ayrıca, Sitelerimiz üzerinde gelecekteki hareketlerinizin hızlanmasına da yardımcı olur. '
             'Bunlara ek olarak, ziyaretçilerin Sitelerimizi nasıl kullandığını anlamak ve Sitelerimizin tasarımını ve '
             'kullanışlılığını geliştirmek amacıyla çerezleri Sitelerimizin kullanımı hakkında istatistiksel bilgiler '
             'toplamak için de kullanabiliriz.</p>\n'
             '\n'
             '<p>&nbsp;</p>\n'
             '\n'
             '<p>{{company_name}}</p>\n'
             '\n'
             '<p>&nbsp;</p>\n'
             '\n'
             '<p>Adresi: -{{address}}</p>\n'
             '\n'
             '<p>Telefonu: {{phone}}</p>'},
 {'slug': 'iletisim',
  'title': 'İletişim',
  'meta_title': 'İletişim | {{store_name}}',
  'meta_description': '{{store_name}} ile iletişime geçin. Sorularınız ve talepleriniz için bize ulaşın.',
  'content': '<p>Bizimle her zaman iletişime geçebilirsiniz. Sorularınız, talepleriniz ve iş birlikleri için aşağıdaki '
             'kanallardan bize ulaşabilirsiniz.</p>\n'
             '<h3>{{company_name}}</h3>\n'
             '<p><strong>Adres:</strong> {{address}}</p>\n'
             '<p><strong>Telefon:</strong> <a href="tel:{{phone_tel}}">{{phone}}</a></p>\n'
             '<p><strong>E-posta:</strong> <a href="mailto:{{email}}">{{email}}</a></p>\n'
             '<p><strong>IBAN:</strong> {{iban}} ({{company_name}})</p>\n'
             '<h3>Müşteri Hizmetleri</h3>\n'
             '<p>Hafta içi 09:00 - 18:00 saatleri arasında e-posta ve telefon üzerinden taleplerinizi yanıtlıyoruz. '
             'Siparişinizle ilgili sorularda sipariş numaranızı belirtmeniz sürecinizi hızlandıracaktır.</p>'},
 {'slug': 'sss',
  'title': 'Sıkça Sorulan Sorular',
  'meta_title': 'Sıkça Sorulan Sorular | {{store_name}}',
  'meta_description': 'Sipariş, kargo, iade, ödeme ve beden hakkında sıkça sorulan sorular ve yanıtları.',
  'content': '<h3>ÜYELİK</h3>\n'
             '<h4>Sipariş vermek için üye olmam gerekiyor mu?</h4>\n'
             '<div>{{store_name}} web sitesinden sipariş verebilmek için birkaç dakikanızı alacak bir üyelik işlemi '
             'gerçekleştirebilirsiniz.<br />\n'
             '<br />\n'
             'Üyelik gerçekleştirmek istemiyorsanız <b>"Üyeliksiz Devam Et"</b> seçeneği ile sipariş '
             'oluşturabilirsiniz.</div>\n'
             '<h4>Neden üye olmalıyım?</h4>\n'
             '<div>Sipariş verebilmeniz ve vermiş olduğunuz siparişlerin durumu hakkında bilgi edinmek, kampanyalardan '
             'haberdar olabilmek, size özel sunulan kampanya ve avantajlardan faydalanabilmek için üye olmanız '
             'gerekmektedir.</div>\n'
             '<h4>Üyelik bilgilerimi nasıl güncelleyebilirim?</h4>\n'
             '<div>Kullanıcı adınız ve şifreniz ile üye girişi yaptıktan sonra <b>"Hesabım"</b> bölümünden üyelik '
             'bilgilerinizi güncelleyebilirsiniz.</div>\n'
             '<h4>Şifremi unuttum, ne yapmalıyım?</h4>\n'
             '<div>Şifrenizi unuttuğunuzda üye girişi bölümünde bulunan <b>"Şifremi Unuttum"</b> linkine tıklamanız ve '
             'karşınıza gelen talimatlara uymanız yeterli olacaktır.</div>\n'
             '<h3>ONLINE ALIŞVERİŞ</h3>\n'
             '<h4>Siparişimin onaylandığını nasıl anlayabilirim?</h4>\n'
             '<div>Siparişiniz alındığında başarıyla gerçekleştiğine dair, kayıtlı e-posta adresinize sipariş '
             'bilgileriniz gönderilmektedir.</div>\n'
             '<h4>Siparişim onaylandıktan sonra değişiklik yapabilir miyim?</h4>\n'
             '<div>Ne yazık ki siparişiniz onaylandıktan sonra siparişinizin bir kısmı ya da tamamı ile ilgili '
             'değişiklik yapamamaktayız.<br />\n'
             '<br />\n'
             'Ancak siparişinizi iptal edip, yeni sipariş verebilirsiniz.</div>\n'
             '<h3>ÖDEME</h3>\n'
             '<h4>Aldığım ürünlerin fiyatlarına KDV dâhil midir?</h4>\n'
             '<div>{{store_name}} sitesi üzerinden satılan her ürünün fiyatına KDV dahildir.</div>\n'
             '<h4>Havale yoluyla ödeme yapabiliyor muyum?</h4>\n'
             '<div>Havale/EFT ile ödeme yapabilirsiniz.</div>\n'
             '<h4>Taksit seçeneğiniz var mı?</h4>\n'
             '<div>ATM/Debit Kart veya kredi kartı bilgilerini eksiksiz doldurduktan sonra, bankanızın sunduğu taksit '
             'seçeneklerini ödeme ekranında görüntüleyebilir, istediğiniz taksit tutarını seçerek taksitli ödemenizi '
             'gerçekleştirebilirsiniz.</div>\n'
             '<h4>Kredi kartı detaylarım güvende midir?</h4>\n'
             '<div>{{site}}, veri iletiminde 128 bit şifreleme ile iletilen bilgilerin güvenliğini sağlayan SSL '
             'sertifikası kullanmaktadır. Kredi kartı bilgileriniz yalnızca sipariş işlemi sırasında kullanılır ve '
             'veri tabanında kayıtlı olarak tutulmaz.<br />\n'
             '<br />\n'
             'Sitemizde gerçekleşen tüm alışveriş işlemleri 3Dsecure özelliği zorunlu halde gerçekleşmektedir.<br />\n'
             '<br />\n'
             'Hesabınıza izinsiz erişimi engellemek için şifrenizi ve hesap detaylarınızı lütfen başkalarıyla '
             'paylaşmayınız.<br />\n'
             '<br />\n'
             '<b>Sorun yaşarsanız:</b> Ödeme işlemlerinde yaşayacağınız olası sorunlarda kart numaranızın tamamını '
             'paylaşmayınız. Sadece sipariş numaranızı iletmeniz yeterlidir ya da bankanızın müşteri hizmetlerinden '
             'bilgi alabilirsiniz.</div>\n'
             '<h3>KARGO VE TESLİMAT</h3>\n'
             '<h4>Hangi kargo firması ile çalışıyorsunuz?</h4>\n'
             '<div>İnternet mağazamızdan oluşturduğunuz siparişleriniz, size anlaşmalı kargo firmamızın güvencesiyle '
             'ulaştırılmaktadır.</div>\n'
             "<h4>Yurt dışına veya KKTC'ye sipariş gönderimi yapılıyor mu?</h4>\n"
             '<div>Yurt dışına gönderiler için lütfen WhatsApp hattımızdan bizlere ulaşınız.</div>\n'
             '<h4>Resmi tatillerde teslimat yapılıyor mu?</h4>\n'
             '<div>Resmi tatillerde kargo firmaları genellikle teslimat yapmamaktadır.</div>\n'
             '<h4>Anlaşmalı kargo firması haricinde başka kargo şirketi ile gönderim yapabiliyor musunuz?</h4>\n'
             '<div>Gönderimler anlaşmalı kargo firmamız ile yapılmaktadır.</div>\n'
             '<h4>Sipariş teslimatında adreste yoksam ne oluyor?</h4>\n'
             '<div>Siparişiniz adresinizde bulunmadığınız için ulaştırılamadıysa kargo firması belirtilen adrese '
             'ikinci bir uğrama yapmamaktadır. Bu durumda kargonuzun bulunduğu şubeyi ziyaret ederek kargonuzu teslim '
             'almanız gerekmektedir.</div>\n'
             '<h4>Paket hasarlı geldi, teslim almalı mıyım?</h4>\n'
             '<div>Hasarlı gelen paketleri teslim almayıp, kargo görevlisine paketin hasarlı olduğuna dair tutanak '
             'tutturmanız gerekmektedir. Daha sonra siparişinizle ilgili müşteri hizmetlerimizle iletişime '
             'geçebilirsiniz.</div>\n'
             '<h3>İADE - DEĞİŞİM</h3>\n'
             '<h4>Ürünlerde iade süresi ne kadar?</h4>\n'
             '<div>İade işleminizi başlatmadan önce, ad-soyad bilgilerinizi belirterek <b>{{phone}}</b> WhatsApp '
             'destek hattımız üzerinden yazılı olarak iade kodunuzu talep etmeniz gerekmektedir.<br />\n'
             '<br />\n'
             '{{site}} web sitemizden aldığınız ürünlerin <b>kullanılmamış</b> ve <b>deforme olmamış</b> olması '
             'şartıyla iade süresi fatura tarihinden itibaren <b>14 gündür</b>.<br />\n'
             '<br />\n'
             'Hijyen koşulları gereği iç giyim, küpe ve kozmetik ürünlerinde iade yapılmamaktadır.</div>\n'
             '<h4>İade işleminde kargo ücreti ödeyecek miyim?</h4>\n'
             '<div>1) Satın alınmış ürün ayıplı/defolu/yanlış şekilde ulaştıysa, anlaşmalı kargo firmamızı kullanmanız '
             'halinde kargo ücretini biz karşılıyoruz. Farklı kargo firması ile gönderimlerde kargo ücretini '
             'karşılamamaktayız.<br />\n'
             '<br />\n'
             '2) Cayma hakkı kapsamında iade etmek isterseniz, iade koşulları sağlandığında anlaşmalı kargomuz ile '
             'göndermeniz durumunda kargo ücretini biz karşılıyoruz.</div>\n'
             '<h4>Siparişim ayıplı/defolu/yanlış gönderilmişse ne yapmalıyım?</h4>\n'
             '<div>Tüm ürünler kargoya teslim edilmeden önce hasar kontrolünden geçmektedir. Nadiren '
             'ayıplı/defolu/yanlış ürün ulaştıysa süreç şu şekilde ilerler:<br />\n'
             '<br />\n'
             'Ürünü, fatura üzerinde bulunan adresimize anlaşmalı kargo firmamız aracılığı ile <b>Müşteri Adı: '
             '{{company_name}}</b> bilgilerini belirterek göndermeniz gerekmektedir.</div>\n'
             '<h4>Kargo paketinin dışı deforme olmuş ve ürünler zarar görmüşse ne yapmalıyım?</h4>\n'
             '<div>Kargo tesliminde ürünü almadan önce dış pakette hasar kontrolü yapın ve hasar varsa mutlaka '
             '<b>"Durum Tespit Tutanağı"</b> hazırlatın.<br />\n'
             '<br />\n'
             'Teslim sonrası fark edilen hasarda ilgili kargo şubesi ile hemen iletişime geçerek tutanak '
             'düzenlenmesini talep edin. Yardım alamıyorsanız en kısa sürede <b>{{phone}}</b> numaramızdan bizi '
             'bilgilendirin.<br />\n'
             '<br />\n'
             'Hasar tespit tutanağı ile ürünü adresimize gönderdiğinizde değişim ya da iade işlemleriniz hızla '
             'tamamlanır.</div>\n'
             '<h4>Ürün iadesi yaptığımda ödediğim tutar bana nasıl iade edilecek?</h4>\n'
             '<div>İade paketiniz ekibimiz tarafından kontrol edildikten sonra iade durumunuzu web sitemiz üzerinden '
             'takip edebilirsiniz.<br />\n'
             '<br />\n'
             '• Kredi kartı: Tek çekim/ taksitli işlemler, işlem tipine uygun şekilde <b>7 iş günü</b> içinde '
             'kartınıza iade edilir.<br />\n'
             '• Debit kart: Tek çekim işlem <b>7 iş günü</b> içinde banka hesabınıza iade edilir.<br />\n'
             '• Sanal kart: Tek çekim işlem <b>7 iş günü</b> içinde kartınıza iade edilir.<br />\n'
             '• Karşı ödemeli gönderimler, iade edilecek bakiyeden düşülür.</div>\n'
             '<h4>Ürün iadesi hesabıma neden geçmedi?</h4>\n'
             '<div>İade sürecinde yaşanabilecek gecikmeler için WhatsApp destek hattımız <b>{{phone}}</b> ile '
             'iletişime geçebilirsiniz.<br />\n'
             '<br />\n'
             '* Tüm iade ve değişim işlemlerinde fatura ibrazı zorunludur.<br />\n'
             '* İade gönderimlerinde anlaşmalı kargo firmamız ile gönderim yapmanız gerekmektedir; diğer kargo '
             'firmaları ile gönderilen kargoların ücretleri firmamız tarafından karşılanmamaktadır.'},
 {'slug': 'iade-kosullari',
  'title': 'İade & Değişim',
  'meta_title': 'İade & Değişim Koşulları | {{store_name}}',
  'meta_description': '{{store_name}} iade ve değişim koşulları, 14 gün cayma hakkı ve iade süreci hakkında bilgi.',
  'content': '<p>{{store_name}} olarak alışveriş deneyiminizden memnun kalmanızı önemsiyoruz. Aşağıda iade ve değişim '
             'koşullarımızı bulabilirsiniz.</p>\n'
             '<h3>Cayma Hakkı</h3>\n'
             '<p>Ürünü teslim aldığınız tarihten itibaren <strong>14 gün</strong> içinde herhangi bir gerekçe '
             'göstermeksizin cayma hakkınızı kullanabilirsiniz.</p>\n'
             '<h3>İade Koşulları</h3>\n'
             '<ul>\n'
             '<li>Ürün kullanılmamış, yıkanmamış ve yeniden satılabilir durumda olmalıdır.</li>\n'
             '<li>Orijinal etiketleri sökülmemiş, ambalajı zarar görmemiş olmalıdır.</li>\n'
             '<li>Hijyen kuralları gereği iç giyim ve mayo/bikini grubu ürünlerde iade kabul edilmemektedir.</li>\n'
             '</ul>\n'
             '<h3>İade Süreci</h3>\n'
             '<p>İade talebinizi oluşturduktan sonra ürünü anlaşmalı kargo ile tarafımıza gönderebilirsiniz. Ürün '
             'tarafımıza ulaşıp incelendikten sonra ödemeniz aynı ödeme yöntemiyle iade edilir. Bankaya bağlı olarak '
             'iade tutarının hesabınıza yansıması birkaç iş günü sürebilir.</p>\n'
             '<h3>Değişim</h3>\n'
             '<p>Beden veya renk değişimi taleplerinizi iade sürecini başlatarak iletebilirsiniz.</p>'},
 {'slug': 'gizlilik',
  'title': 'Gizlilik Politikası',
  'meta_title': 'Gizlilik Politikası | {{store_name}}',
  'meta_description': '{{store_name}} gizlilik politikası: kişisel verilerinizin toplanması, kullanımı ve korunması.',
  'content': '<p>{{company_name}} olarak gizliliğinize önem veriyoruz. Bu politika, web sitemizi kullanırken kişisel '
             'verilerinizin nasıl toplandığını, kullanıldığını ve korunduğunu açıklar.</p>\n'
             '<h3>Toplanan Veriler</h3>\n'
             '<p>Üyelik, sipariş ve iletişim süreçlerinde ad-soyad, iletişim bilgileri, teslimat adresi ve sipariş '
             'bilgileri gibi veriler işlenir.</p>\n'
             '<h3>Kullanım Amacı</h3>\n'
             '<p>Verileriniz; siparişlerinizin işlenmesi, teslimat, müşteri hizmetleri, yasal yükümlülükler ve izin '
             'vermeniz halinde pazarlama iletişimi amacıyla kullanılır.</p>\n'
             '<h3>Veri Güvenliği</h3>\n'
             '<p>Verileriniz yetkisiz erişime karşı uygun teknik ve idari tedbirlerle korunur. Ödeme bilgileriniz '
             'güvenli ödeme altyapısı üzerinden işlenir ve tarafımızca saklanmaz.</p>\n'
             '<h3>Haklarınız</h3>\n'
             '<p>6698 sayılı KVKK kapsamındaki haklarınız için <a href="/sayfa/kvkk">KVKK Aydınlatma Metni</a> '
             'sayfamızı inceleyebilirsiniz.</p>'},
 {'slug': 'mesafeli-satis',
  'title': 'Mesafeli Satış Sözleşmesi',
  'meta_title': 'Mesafeli Satış Sözleşmesi | {{store_name}}',
  'meta_description': '{{store_name}} mesafeli satış sözleşmesi; taraflar, cayma hakkı ve teslimat koşulları.',
  'content': '<h3>MADDE 1- TARAFLAR</h3>\n'
             '<p><strong>1.1- SATICI:</strong></p>\n'
             '<p>Ünvanı: {{company_name}}<br>Adresi: {{address}}<br>Telefon: {{phone}}<br>E-posta: {{email}}</p>\n'
             "<p><strong>1.2- ALICI:</strong> Siparişi veren müşteri. ALICI'ya ait ad-soyad/ünvan, adres ve iletişim "
             'bilgileri sipariş özetinde ve sipariş onay e-postasında yer alır.</p>\n'
             '<h3>MADDE 2- KONU</h3>\n'
             "<p>İşbu sözleşmenin konusu, ALICI'nın SATICI'ya ait {{company_name}} internet sitesinden elektronik "
             'ortamda siparişini yaptığı, nitelikleri ve satış fiyatı sipariş özetinde belirtilen ürünün satışı ve '
             'teslimi ile ilgili olarak 6502 sayılı Tüketicinin Korunması Hakkında Kanun ve Mesafeli Sözleşmeler '
             'Yönetmeliği hükümleri gereğince tarafların hak ve yükümlülüklerinin saptanmasıdır.</p>\n'
             '<h3>MADDE 3- SÖZLEŞME KONUSU ÜRÜN</h3>\n'
             '<p>Ürünlerin cinsi ve türü, miktarı, marka/modeli, rengi ve satış bedeli sipariş özetinde belirtildiği '
             "gibidir. Ödeme şekli ve teslimat adresi, ALICI'nın sipariş sırasında seçtiği bilgilerdir. Tüm ürün "
             'fiyatlarına KDV dahildir.</p>\n'
             '<h3>MADDE 4- GENEL HÜKÜMLER</h3>\n'
             '<p>4.1- ALICI, {{company_name}} internet sitesinde sözleşme konusu ürünün temel nitelikleri, satış '
             'fiyatı ve ödeme şekli ile teslimata ilişkin ön bilgileri okuyup bilgi sahibi olduğunu ve elektronik '
             'ortamda gerekli teyidi verdiğini beyan eder.</p>\n'
             "<p>4.2- Sözleşme konusu ürün, yasal 30 günlük süreyi aşmamak koşulu ile ALICI'nın yerleşim yerinin "
             'uzaklığına bağlı olarak internet sitesinde ön bilgiler içinde açıklanan süre içinde ALICI veya '
             'gösterdiği adresteki kişi/kuruluşa teslim edilir.</p>\n'
             "<p>4.3- Sözleşme konusu ürün, ALICI'dan başka bir kişi/kuruluşa teslim edilecek ise, teslim edilecek "
             'kişi/kuruluşun teslimatı kabul etmemesinden SATICI sorumlu tutulamaz.</p>\n'
             '<p>4.4- SATICI, sözleşme konusu ürünün sağlam, eksiksiz, siparişte belirtilen niteliklere uygun ve varsa '
             'garanti belgeleri ve kullanım kılavuzları ile teslim edilmesinden sorumludur.</p>\n'
             "<p>4.5- Sözleşme konusu ürünün teslimatı için bedelinin ALICI'nın tercih ettiği ödeme şekli ile ödenmiş "
             'olması şarttır. Herhangi bir nedenle ürün bedeli ödenmez veya banka kayıtlarında iptal edilir ise, '
             'SATICI ürünün teslimi yükümlülüğünden kurtulmuş kabul edilir.</p>\n'
             "<p>4.6- Ürünün tesliminden sonra ALICI'ya ait kredi kartının ALICI'nın kusurundan kaynaklanmayan bir "
             'şekilde yetkisiz kişilerce haksız veya hukuka aykırı olarak kullanılması nedeni ile ilgili banka veya '
             "finans kuruluşunun ürün bedelini SATICI'ya ödememesi halinde, ALICI'nın kendisine teslim edilmiş olması "
             "kaydıyla ürünün 3 gün içinde SATICI'ya gönderilmesi zorunludur. Bu takdirde nakliye giderleri ALICI'ya "
             'aittir.</p>\n'
             '<p>4.7- SATICI mücbir sebepler veya nakliyeyi engelleyen hava muhalefeti, ulaşımın kesilmesi gibi '
             "olağanüstü durumlar nedeni ile sözleşme konusu ürünü süresi içinde teslim edemez ise, durumu ALICI'ya "
             'bildirmekle yükümlüdür. Bu takdirde ALICI siparişin iptal edilmesini, sözleşme konusu ürünün varsa '
             'emsali ile değiştirilmesini ve/veya teslimat süresinin engelleyici durumun ortadan kalkmasına kadar '
             "ertelenmesi haklarından birini kullanabilir. ALICI'nın siparişi iptal etmesi halinde ödediği tutar 14 "
             'gün içinde kendisine nakden ve defaten ödenir.</p>\n'
             '<p>4.8- Garanti belgesi ile satılan ürünlerden arızalı veya bozuk olanlar, garanti şartları içinde '
             "gerekli onarımın yapılması için SATICI'ya gönderilebilir; bu takdirde kargo giderleri SATICI tarafından "
             'karşılanır.</p>\n'
             '<h3>MADDE 5- CAYMA HAKKI</h3>\n'
             '<p>ALICI, sözleşme konusu ürünün kendisine veya gösterdiği adresteki kişi/kuruluşa tesliminden itibaren '
             '14 gün içinde herhangi bir gerekçe göstermeksizin cayma hakkına sahiptir. Cayma hakkının kullanılması '
             "için bu süre içinde SATICI'ya e-posta, telefon veya WhatsApp ({{phone}}) ile bildirimde bulunulması ve "
             'ürünün 6. madde hükümleri çerçevesinde kullanılmamış olması şarttır. Bu hakkın kullanılması halinde, '
             "ürünün SATICI'ya gönderildiğine ilişkin kargo teslim tutanağı örneği ile fatura aslının iadesi "
             "zorunludur. Bu belgelerin ulaşmasını takip eden 14 gün içinde ürün bedeli ALICI'ya iade edilir. Cayma "
             'hakkı nedeni ile iade edilen ürünün anlaşmalı kargo ile gönderilmesi halinde kargo bedeli SATICI '
             'tarafından karşılanır.</p>\n'
             '<h3>MADDE 6- CAYMA HAKKI KULLANILAMAYACAK ÜRÜNLER</h3>\n'
             '<p>Niteliği itibarıyla iade edilemeyecek ürünlerde cayma hakkı kullanılamaz. Aşağıdaki ürünlerde, hijyen '
             've sağlık koşulları gereği, ambalajı/etiketi açılmış veya kullanılmış olması halinde cayma hakkı '
             'kullanılamaz:</p>\n'
             '<ul>\n'
             '<li>İç giyim ürünleri</li>\n'
             '<li>Mayo ve bikini grubu ürünler</li>\n'
             '<li>Küpe ve tekli takılar</li>\n'
             '<li>Her türlü kozmetik ürünü</li>\n'
             '</ul>\n'
             "<p>Ayrıca ALICI'nın istekleri doğrultusunda kişiye özel hazırlanan ürünler cayma hakkı kapsamı "
             'dışındadır.</p>\n'
             '<h3>MADDE 7- YETKİLİ MAHKEME</h3>\n'
             "<p>İşbu sözleşmenin uygulanmasında, Ticaret Bakanlığınca ilan edilen değere kadar ALICI'nın veya "
             "SATICI'nın yerleşim yerindeki Tüketici Hakem Heyetleri ile Tüketici Mahkemeleri yetkilidir.</p>\n"
             '<p>Siparişin gerçekleşmesi durumunda ALICI işbu sözleşmenin tüm koşullarını kabul etmiş sayılır.</p>'},
 {'slug': 'on-bilgilendirme',
  'title': 'Ön Bilgilendirme Koşulları',
  'meta_title': 'Ön Bilgilendirme Koşulları | {{store_name}}',
  'meta_description': '{{store_name}} ön bilgilendirme formu; satıcı bilgileri, cayma hakkı ve teslimat.',
  'content': '<h3>MADDE 1- TARAFLAR</h3>\n'
             '<p><strong>1.1- SATICI:</strong></p>\n'
             '<p>Ünvanı: {{company_name}}<br>Adresi: {{address}}<br>Telefon: {{phone}}<br>E-posta: {{email}}</p>\n'
             "<p><strong>1.2- ALICI:</strong> Siparişi veren müşteri. ALICI'ya ait ad-soyad/ünvan, teslimat adresi ve "
             'iletişim bilgileri sipariş özetinde ve sipariş onay e-postasında yer alır.</p>\n'
             '<h3>MADDE 2- KONU</h3>\n'
             "<p>İşbu Ön Bilgilendirme Formu'nun konusu, ALICI'nın SATICI'ya ait {{company_name}} internet sitesinden "
             'elektronik ortamda siparişini yaptığı, nitelikleri ve satış fiyatı sipariş özetinde belirtilen ürünün '
             'satışı ve teslimi ile ilgili olarak 6502 sayılı Tüketicinin Korunması Hakkında Kanun ve Mesafeli '
             "Sözleşmeler Yönetmeliği hükümleri gereğince tarafların hak ve yükümlülükleri hakkında ALICI'nın "
             'bilgilendirilmesidir.</p>\n'
             '<h3>MADDE 3- SÖZLEŞME KONUSU ÜRÜN</h3>\n'
             '<p>Ürünlerin cinsi ve türü, miktarı, marka/modeli, rengi ve satış bedeli sipariş özetinde belirtildiği '
             "gibidir. Ödeme şekli ve teslimat adresi, ALICI'nın sipariş sırasında seçtiği bilgilerdir. Tüm ürün "
             'fiyatlarına KDV dahildir. Ürün bedeline ek olarak tahsil edilecek kargo/teslimat bedeli varsa sipariş '
             'özetinde ayrıca gösterilir.</p>\n'
             '<h3>MADDE 4- GENEL HÜKÜMLER</h3>\n'
             '<p>4.1- ALICI, {{company_name}} internet sitesinde sözleşme konusu ürünün temel nitelikleri, satış '
             'fiyatı ve ödeme şekli ile teslimata ilişkin ön bilgileri okuyup bilgi sahibi olduğunu ve elektronik '
             'ortamda gerekli teyidi verdiğini beyan eder.</p>\n'
             "<p>4.2- Sözleşme konusu ürün, yasal 30 günlük süreyi aşmamak koşulu ile ALICI'nın yerleşim yerinin "
             'uzaklığına bağlı olarak internet sitesinde ön bilgiler içinde açıklanan süre içinde ALICI veya '
             'gösterdiği adresteki kişi/kuruluşa teslim edilir.</p>\n'
             "<p>4.3- Sözleşme konusu ürün, ALICI'dan başka bir kişi/kuruluşa teslim edilecek ise, teslim edilecek "
             'kişi/kuruluşun teslimatı kabul etmemesinden SATICI sorumlu tutulamaz.</p>\n'
             '<p>4.4- SATICI, sözleşme konusu ürünün sağlam, eksiksiz, siparişte belirtilen niteliklere uygun ve varsa '
             'garanti belgeleri ve kullanım kılavuzları ile teslim edilmesinden sorumludur.</p>\n'
             "<p>4.5- Sözleşme konusu ürünün teslimatı için bedelinin ALICI'nın tercih ettiği ödeme şekli ile ödenmiş "
             'olması şarttır. Herhangi bir nedenle ürün bedeli ödenmez veya banka kayıtlarında iptal edilir ise, '
             'SATICI ürünün teslimi yükümlülüğünden kurtulmuş kabul edilir.</p>\n'
             "<p>4.6- Ürünün tesliminden sonra ALICI'ya ait kredi kartının ALICI'nın kusurundan kaynaklanmayan bir "
             'şekilde yetkisiz kişilerce haksız veya hukuka aykırı olarak kullanılması nedeni ile ilgili banka veya '
             "finans kuruluşunun ürün bedelini SATICI'ya ödememesi halinde, ALICI'nın kendisine teslim edilmiş olması "
             "kaydıyla ürünün 3 gün içinde SATICI'ya gönderilmesi zorunludur. Bu takdirde nakliye giderleri ALICI'ya "
             'aittir.</p>\n'
             '<p>4.7- SATICI mücbir sebepler veya nakliyeyi engelleyen hava muhalefeti, ulaşımın kesilmesi gibi '
             "olağanüstü durumlar nedeni ile sözleşme konusu ürünü süresi içinde teslim edemez ise, durumu ALICI'ya "
             'bildirmekle yükümlüdür. Bu takdirde ALICI siparişin iptal edilmesini, sözleşme konusu ürünün varsa '
             'emsali ile değiştirilmesini ve/veya teslimat süresinin engelleyici durumun ortadan kalkmasına kadar '
             "ertelenmesi haklarından birini kullanabilir. ALICI'nın siparişi iptal etmesi halinde ödediği tutar 14 "
             'gün içinde kendisine nakden ve defaten ödenir.</p>\n'
             '<p>4.8- Garanti belgesi ile satılan ürünlerden arızalı veya bozuk olanlar, garanti şartları içinde '
             "gerekli onarımın yapılması için SATICI'ya gönderilebilir; bu takdirde kargo giderleri SATICI tarafından "
             'karşılanır.</p>\n'
             '<h3>MADDE 5- CAYMA HAKKI</h3>\n'
             '<p>ALICI, sözleşme konusu ürünün kendisine veya gösterdiği adresteki kişi/kuruluşa tesliminden itibaren '
             '14 gün içinde herhangi bir gerekçe göstermeksizin cayma hakkına sahiptir. Cayma hakkının kullanılması '
             "için bu süre içinde SATICI'ya e-posta, telefon veya WhatsApp ({{phone}}) ile bildirimde bulunulması ve "
             'ürünün 6. madde hükümleri çerçevesinde kullanılmamış olması şarttır. Bu hakkın kullanılması halinde, '
             "ürünün SATICI'ya gönderildiğine ilişkin kargo teslim tutanağı örneği ile fatura aslının iadesi "
             "zorunludur. Bu belgelerin ulaşmasını takip eden 14 gün içinde ürün bedeli ALICI'ya iade edilir. Cayma "
             'hakkı nedeni ile iade edilen ürünün anlaşmalı kargo ile gönderilmesi halinde kargo bedeli SATICI '
             'tarafından karşılanır.</p>\n'
             '<h3>MADDE 6- CAYMA HAKKI KULLANILAMAYACAK ÜRÜNLER</h3>\n'
             '<p>Niteliği itibarıyla iade edilemeyecek ürünlerde cayma hakkı kullanılamaz. Aşağıdaki ürünlerde, hijyen '
             've sağlık koşulları gereği, ambalajı/etiketi açılmış veya kullanılmış olması halinde cayma hakkı '
             'kullanılamaz:</p>\n'
             '<ul>\n'
             '<li>İç giyim ürünleri</li>\n'
             '<li>Mayo ve bikini grubu ürünler</li>\n'
             '<li>Küpe ve tekli takılar</li>\n'
             '<li>Her türlü kozmetik ürünü</li>\n'
             '</ul>\n'
             "<p>Ayrıca ALICI'nın istekleri doğrultusunda kişiye özel hazırlanan ürünler cayma hakkı kapsamı "
             'dışındadır.</p>\n'
             '<h3>MADDE 7- YETKİLİ MAHKEME</h3>\n'
             "<p>İşbu formun uygulanmasında, Ticaret Bakanlığınca ilan edilen değere kadar ALICI'nın veya SATICI'nın "
             'yerleşim yerindeki Tüketici Hakem Heyetleri ile Tüketici Mahkemeleri yetkilidir.</p>\n'
             "<p>Siparişi onaylayarak işbu Ön Bilgilendirme Formu'nu okuduğunuzu ve kabul ettiğinizi beyan etmiş "
             'olursunuz.</p>'}]
