import { SITE_NAME } from "../../lib/brand";
import React, { useEffect, useMemo, useRef, useState } from "react";
import axios from "axios";
import { toast } from "sonner";
import { Palette, Eye, CheckCircle2, Trash2, RotateCcw, Plus, GripVertical, Upload, ExternalLink, ArrowLeft, Save, Monitor, Smartphone, History, X } from "lucide-react";
import { themeCssVariables, themeImage, themePrice } from "../../lib/themeGallery";
import "./themeGallery.css";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const BLOCK_TYPES = [
  ["announcement_bar","Duyuru Bandı"],["hero_fullscreen","Hero"],["editorial_card","Editöryel Kart"],
  ["product_scroller","Ürün Şeridi"],["newsletter","Bülten"],["text_section","Metin Bölümü"],
];

export default function Themes() {
  const [list,setList]=useState([]), [data,setData]=useState({company:{name:SITE_NAME},categories:[],products:[]});
  const [loading,setLoading]=useState(true), [editing,setEditing]=useState(null), [preview,setPreview]=useState(null);
  const [viewport,setViewport]=useState("desktop"), [versions,setVersions]=useState([]), [showHistory,setShowHistory]=useState(false);
  const active=useMemo(()=>list.find(t=>t.is_active),[list]);

  const fetchAll=async()=>{ setLoading(true); try { const [themes,previewData]=await Promise.all([axios.get(`${API}/admin/themes`),axios.get(`${API}/admin/themes/preview-data`)]); setList(themes.data.items||[]); setData(previewData.data||data); } catch(e){ toast.error(e.response?.data?.detail||"Tema galerisi yüklenemedi"); } finally { setLoading(false); }};
  useEffect(()=>{fetchAll();},[]); // eslint-disable-line react-hooks/exhaustive-deps

  const apply=async(theme)=>{
    if(!window.confirm(`“${theme.name}” temasını canlı mağazada uygulamak üzeresiniz. Mevcut tema sürüm olarak saklanacak ve geri alınabilecektir. Devam edilsin mi?`)) return;
    try { const r=await axios.post(`${API}/admin/themes/${theme.id}/activate`,{confirm:true,expected_current_theme_id:active?.id||null}); toast.success(`Tema uygulandı. Geri alma sürümü: ${r.data.rollback_version_id||"mevcut"}`); await fetchAll(); }
    catch(e){ toast.error(e.response?.data?.detail||"Tema uygulanamadı"); }
  };
  const remove=async theme=>{ if(!window.confirm(`“${theme.name}” temasını silmek istiyor musunuz?`))return; try{await axios.delete(`${API}/admin/themes/${theme.id}`);toast.success("Tema silindi");fetchAll();}catch(e){toast.error(e.response?.data?.detail||"Tema silinemedi");}};
  const reset=async id=>{ if(!window.confirm("Bu temayı özgün fabrika ayarlarına döndürmek istiyor musunuz? Önce mevcut sürüm saklanacaktır."))return; try{const r=await axios.post(`${API}/admin/themes/${id}/reset`);setEditing(r.data);toast.success("Tema sıfırlandı; önceki sürüm saklandı");fetchAll();}catch(e){toast.error(e.response?.data?.detail||"Tema sıfırlanamadı");}};
  const openHistory=async()=>{try{const r=await axios.get(`${API}/admin/themes/versions`);setVersions(r.data.items||[]);setShowHistory(true);}catch{toast.error("Sürüm geçmişi yüklenemedi");}};
  const rollback=async v=>{if(!window.confirm(`“${v.theme_name}” temasının ${new Date(v.created_at).toLocaleString("tr-TR")} sürümüne dönülsün mü? Mevcut durum da saklanacaktır.`))return;try{await axios.post(`${API}/admin/themes/versions/${v.id}/rollback`,{confirm:true});toast.success("Tema sürümü geri yüklendi");setShowHistory(false);fetchAll();}catch(e){toast.error(e.response?.data?.detail||"Geri alma başarısız");}};

  if(editing) return <ThemeEditor initial={editing} data={data} onClose={()=>{setEditing(null);fetchAll();}} onReset={reset}/>;
  return <div className="space-y-6" data-testid="themes-page">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold flex items-center gap-2"><Palette size={24}/> Tema Yönetimi</h1><p className="text-sm text-zinc-500 mt-1">Gerçek logo, kategori ve ürünlerle canlı önizleme. Önizleme değişiklik yapmaz; yalnız “Uygula” mağazayı değiştirir.</p></div><button onClick={openHistory} className="px-3 py-2 border rounded flex items-center gap-2 text-sm"><History size={15}/> Sürüm geçmişi</button></div>
    <div className="flex items-center justify-between rounded-xl border bg-white p-3"><div className="text-xs text-zinc-600"><b>Önizleme verisi:</b> {data.company?.name} · {data.categories?.length||0} kategori · {data.products?.length||0} gerçek ürün</div><ViewportToggle value={viewport} onChange={setViewport}/></div>
    {loading?<div>Yükleniyor…</div>:<div className="grid grid-cols-1 xl:grid-cols-3 gap-5">{list.map(theme=><ThemeCard key={theme.id} theme={theme} data={data} viewport={viewport} onPreview={()=>setPreview(theme)} onEdit={()=>setEditing(theme)} onApply={()=>apply(theme)} onDelete={()=>remove(theme)}/>)}</div>}
    {preview&&<PreviewModal theme={preview} data={data} viewport={viewport} setViewport={setViewport} onClose={()=>setPreview(null)} onEdit={()=>{setEditing(preview);setPreview(null);}}/>}
    {showHistory&&<HistoryModal versions={versions} onRollback={rollback} onClose={()=>setShowHistory(false)}/>}
  </div>;
}

function ViewportToggle({value,onChange}) { return <div className="flex rounded-lg border p-1" aria-label="Önizleme boyutu">{[["desktop",Monitor,"Masaüstü"],["mobile",Smartphone,"Mobil"]].map(([v,I,l])=><button key={v} onClick={()=>onChange(v)} aria-pressed={value===v} className={`px-2 py-1 rounded flex items-center gap-1 text-xs ${value===v?"bg-zinc-900 text-white":""}`}><I size={13}/>{l}</button>)}</div>; }

function ThemeCard({theme,data,viewport,onPreview,onEdit,onApply,onDelete}) { return <article className="bg-white border rounded-xl overflow-hidden shadow-sm" data-testid={`theme-card-${theme.slug}`}>
  <div className="h-64 bg-zinc-100 p-3 overflow-hidden"><MiniPreview theme={theme} data={data} viewport={viewport}/></div>
  <div className="p-4"><div className="flex justify-between gap-2"><div><h2 className="font-semibold">{theme.name}</h2><p className="text-xs text-zinc-500 mt-1 min-h-8">{theme.description}</p></div>{theme.is_active&&<span className="h-fit bg-emerald-100 text-emerald-800 rounded-full px-2 py-1 text-[11px] flex items-center gap-1"><CheckCircle2 size={12}/>Aktif</span>}</div>
    <div className="grid grid-cols-2 gap-2 mt-4"><button onClick={onPreview} className="border rounded py-2 text-xs flex justify-center gap-1"><Eye size={13}/>Önizle</button><button onClick={onEdit} className="border rounded py-2 text-xs">Özelleştir</button>{!theme.is_active&&<button onClick={onApply} className="col-span-2 bg-zinc-900 text-white rounded py-2 text-xs font-semibold">Uygula</button>}{!theme.is_default&&!theme.is_active&&<button onClick={onDelete} className="col-span-2 text-rose-600 border border-rose-200 rounded py-2 text-xs flex justify-center gap-1"><Trash2 size={13}/>Sil</button>}</div>
  </div></article>; }

function MiniPreview({theme,data,viewport,page="home"}) { const products=data.products||[], cats=data.categories||[], company=data.company||{}; return <div className={`tg-preview tg-${viewport}`} data-layout={theme.settings?.layout||"editorial"} style={themeCssVariables(theme.settings?.tokens)}>
  <header><div className="tg-mark">{company.logo_url?<img src={company.logo_url} alt=""/>:company.name}</div><nav>{cats.slice(0,4).map(c=><span key={c.id}>{c.name}</span>)}</nav><b>⌕　♡　▢</b></header>
  {page==="home"&&<><section className="tg-hero" style={{backgroundImage:`linear-gradient(#0004,#0004),url(${theme.blocks?.find(b=>b.type==="hero_fullscreen")?.image||themeImage(products[0])})`}}><small>SEÇKİ</small><h3>{theme.blocks?.find(b=>b.type==="hero_fullscreen")?.title||"Yeni sezon"}</h3><button>KEŞFET</button></section><PreviewGrid products={products}/></>}
  {page==="category"&&<><div className="tg-page-title"><small>KOLEKSİYON</small><h3>{cats[0]?.name||"Tüm ürünler"}</h3></div><PreviewGrid products={products}/></>}
  {page==="product"&&<ProductPreview product={products[0]}/>}
  {!products.length&&page!=="home"&&<div className="tg-empty">Katalogda gösterilebilir ürün bulunamadı.</div>}
  </div>; }
function PreviewGrid({products}) { return <section className="tg-grid">{products.slice(0,4).map(p=><div key={p.id}><div style={{backgroundImage:`url(${themeImage(p)})`}}/><b>{p.name||p.title}</b><span>{themePrice(p)}</span></div>)}</section>; }
function ProductPreview({product}) { if(!product)return null; return <section className="tg-product"><div style={{backgroundImage:`url(${themeImage(product)})`}}/><aside><small>YENİ SEZON</small><h3>{product.name||product.title}</h3><b>{themePrice(product)}</b><p>Renk ve beden seçeneklerini keşfedin.</p><button>SEPETE EKLE</button></aside></section>; }

function PreviewModal({theme,data,viewport,setViewport,onClose,onEdit}) { const [page,setPage]=useState("home"); return <div className="fixed inset-0 z-[100] bg-black/60 p-4 md:p-8 flex items-center justify-center" role="dialog" aria-modal="true"><div className="bg-white rounded-xl w-full max-w-6xl max-h-full overflow-auto"><div className="sticky top-0 z-10 bg-white border-b p-3 flex flex-wrap justify-between gap-2"><div><b>{theme.name}</b><div className="flex gap-1 mt-2">{[["home","Ana sayfa"],["category","Kategori"],["product","Ürün detayı"]].map(([v,l])=><button key={v} onClick={()=>setPage(v)} className={`px-2 py-1 rounded text-xs ${page===v?"bg-zinc-900 text-white":"bg-zinc-100"}`}>{l}</button>)}</div></div><div className="flex items-center gap-2"><ViewportToggle value={viewport} onChange={setViewport}/><button onClick={onEdit} className="border rounded px-3 py-2 text-xs">Özelleştir</button><a href={`/tema/${theme.slug}`} target="_blank" rel="noreferrer" className="border rounded px-3 py-2 text-xs flex gap-1"><ExternalLink size={13}/>Tam ekran</a><button onClick={onClose} aria-label="Kapat"><X/></button></div></div><div className={`mx-auto p-5 ${viewport==="mobile"?"max-w-sm":"max-w-full"}`}><MiniPreview theme={theme} data={data} viewport={viewport} page={page}/></div></div></div>; }

function HistoryModal({versions,onRollback,onClose}) { return <div className="fixed inset-0 z-[100] bg-black/50 flex justify-end" role="dialog" aria-modal="true"><aside className="w-full max-w-md bg-white h-full p-5 overflow-auto"><div className="flex justify-between"><h2 className="font-bold">Tema sürüm geçmişi</h2><button onClick={onClose} aria-label="Kapat"><X/></button></div><p className="text-xs text-zinc-500 mt-2">Her uygulama ve özelleştirme öncesindeki geri alınabilir kopyalar.</p><div className="mt-5 space-y-3">{versions.map(v=><div key={v.id} className="border rounded p-3"><b className="text-sm">{v.theme_name}</b><p className="text-xs text-zinc-500">{v.action} · {new Date(v.created_at).toLocaleString("tr-TR")}</p><button onClick={()=>onRollback(v)} className="mt-2 text-xs border rounded px-2 py-1"><RotateCcw size={12} className="inline"/> Bu sürüme dön</button></div>)}{!versions.length&&<p className="text-sm text-zinc-500">Henüz sürüm kaydı yok.</p>}</div></aside></div>; }

function ThemeEditor({initial,data,onClose,onReset}) { const [theme,setTheme]=useState(initial),[saving,setSaving]=useState(false),[viewport,setViewport]=useState("desktop"); const blocks=theme.blocks||[];
 const updateBlock=(id,patch)=>setTheme(t=>({...t,blocks:t.blocks.map(b=>b.id===id?{...b,...patch}:b)}));
 const move=(idx,dir)=>{const next=[...blocks],to=idx+dir;if(to<0||to>=next.length)return;[next[idx],next[to]]=[next[to],next[idx]];next.forEach((b,i)=>b.order=i);setTheme({...theme,blocks:next});};
 const save=async()=>{setSaving(true);try{const r=await axios.put(`${API}/admin/themes/${theme.id}`,{name:theme.name,slug:theme.slug,description:theme.description,preview_image:theme.preview_image,blocks:theme.blocks,menu:theme.menu,settings:theme.settings});setTheme(r.data);toast.success("Tema taslağı kaydedildi; canlı tema değiştirilmedi");}catch(e){toast.error(e.response?.data?.detail||"Kaydedilemedi");}finally{setSaving(false);}};
 return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div className="flex gap-2"><button onClick={onClose}><ArrowLeft/></button><div><h1 className="text-xl font-bold">{theme.name}</h1><p className="text-xs text-zinc-500">Özelleştirme taslağı</p></div></div><div className="flex gap-2"><button onClick={()=>onReset(theme.id)} className="border rounded px-3 py-2 text-xs"><RotateCcw size={13} className="inline"/> Fabrika ayarları</button><button onClick={save} disabled={saving} className="bg-zinc-900 text-white rounded px-4 py-2 text-xs"><Save size={13} className="inline"/> {saving?"Kaydediliyor…":"Taslağı kaydet"}</button></div></div>
 <div className="grid xl:grid-cols-2 gap-5"><div className="space-y-4"><div className="bg-white border rounded p-4 grid gap-3"><label className="text-xs font-semibold">Tema adı<input value={theme.name} onChange={e=>setTheme({...theme,name:e.target.value})} className="block w-full border rounded p-2 mt-1 font-normal"/></label><label className="text-xs font-semibold">Açıklama<textarea value={theme.description||""} onChange={e=>setTheme({...theme,description:e.target.value})} className="block w-full border rounded p-2 mt-1 font-normal"/></label><TokenFields theme={theme} setTheme={setTheme}/></div><div className="flex justify-between"><h2 className="font-semibold text-sm">İçerik blokları</h2><button onClick={()=>setTheme({...theme,blocks:[...blocks,{id:`tmp-${Date.now()}`,type:"text_section",title:"Yeni bölüm",subtitle:"",order:blocks.length,is_active:true,settings:{}}]})} className="text-xs border rounded px-2"><Plus size={12} className="inline"/> Blok ekle</button></div>{blocks.map((b,i)=><BlockRow key={b.id} block={b} idx={i} total={blocks.length} onChange={p=>updateBlock(b.id,p)} onMove={d=>move(i,d)} onRemove={()=>setTheme({...theme,blocks:blocks.filter(x=>x.id!==b.id)})}/>)}</div><div className="xl:sticky xl:top-4 h-fit"><div className="flex justify-between mb-2"><b className="text-sm">Canlı taslak önizlemesi</b><ViewportToggle value={viewport} onChange={setViewport}/></div><MiniPreview theme={theme} data={data} viewport={viewport}/></div></div></div>; }

function TokenFields({theme,setTheme}) { const tokens=theme.settings?.tokens||{}; const set=(k,v)=>setTheme({...theme,settings:{...theme.settings,tokens:{...tokens,[k]:v}}}); return <div><p className="text-xs font-semibold mb-2">Tema renkleri (CSS değişkenleri)</p><div className="grid grid-cols-3 gap-2">{[["background","Arka plan"],["surface","Yüzey"],["text","Metin"],["muted","İkincil"],["accent","Vurgu"],["border","Çizgi"]].map(([k,l])=><label key={k} className="text-[11px]">{l}<span className="flex border rounded p-1 mt-1"><input type="color" value={tokens[k]||"#000000"} onChange={e=>set(k,e.target.value)}/><input value={tokens[k]||""} onChange={e=>set(k,e.target.value)} className="w-full text-[10px] px-1"/></span></label>)}</div></div>; }

function BlockRow({block,idx,total,onChange,onMove,onRemove}) { const inputRef=useRef(); const upload=async file=>{const fd=new FormData();fd.append("file",file);try{const r=await axios.post(`${API}/upload`,fd,{headers:{"Content-Type":"multipart/form-data"}});const u=r.data.url||r.data.file_url||r.data.path;if(u)onChange({image:u.startsWith("http")?u:`${process.env.REACT_APP_BACKEND_URL}${u}`});}catch{toast.error("Görsel yüklenemedi");}}; return <div className="bg-white border rounded p-3"><div className="flex gap-2 items-center"><GripVertical size={14}/><div><button disabled={!idx} onClick={()=>onMove(-1)}>▲</button><button disabled={idx===total-1} onClick={()=>onMove(1)}>▼</button></div><select value={block.type} onChange={e=>onChange({type:e.target.value})} className="border rounded p-1 text-xs">{BLOCK_TYPES.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><input value={block.title||""} onChange={e=>onChange({title:e.target.value})} className="border rounded p-1 flex-1 text-sm"/><button onClick={onRemove} className="text-rose-600"><Trash2 size={14}/></button></div><div className="grid grid-cols-2 gap-2 mt-2"><input value={block.subtitle||""} onChange={e=>onChange({subtitle:e.target.value})} placeholder="Alt başlık" className="border rounded p-2 text-xs"/><input value={block.link_label||""} onChange={e=>onChange({link_label:e.target.value})} placeholder="Buton metni" className="border rounded p-2 text-xs"/>{["hero_fullscreen","editorial_card"].includes(block.type)&&<><input value={block.image||""} onChange={e=>onChange({image:e.target.value})} placeholder="Görsel URL" className="border rounded p-2 text-xs"/><button onClick={()=>inputRef.current?.click()} className="border rounded text-xs"><Upload size={12} className="inline"/> Görsel yükle</button><input ref={inputRef} type="file" accept="image/*" hidden onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></>}</div></div>; }
